// Style
import './globals.scss';
// Librairies
import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
// App
import { roboto, montserrat } from '~/fonts';
import { Header } from '~/components';
import { Locale, PageProps } from '~/types';
import { availableLocales } from '~/utils';
import { AuthProvider } from '~/providers';

export const metadata: Metadata = {
    title: {
        template: '%s | CineSwipe',
        default: 'Welcome to CineSwipe',
    },
    description: 'Generated by create next app',
};

export const generateStaticParams = () => availableLocales.map((locale) => ({ locale }));

export default function RootLayout({ children, params: { locale } }: PropsWithChildren<PageProps<{ locale: Locale }>>) {
    return (
        <html lang={locale}>
            <body className={`${roboto.variable} ${montserrat.variable}`}>
                <AuthProvider>
                    <Header locale={locale} />
                    <main>{children}</main>
                </AuthProvider>
            </body>
        </html>
    );
}
